### ISSUE TITLE
error on report when running with --role master

### ISSUE THREAD

**Issue by ochriste** [sbrunner/tilecloud-chain#226]
when running with the `--role` master options, there is an error when generating the final report:
```
Traceback (most recent call last):
  File "./bin/generate_tiles", line 12, in <module>
    load_entry_point('tilecloud-chain==1.0.0dev1', 'console_scripts', 'generate_tiles')()
  File "/var/www/vhosts/tileforge/private/veloland/veloland/tilecloud/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 421, in main
    generate.gene(options, gene, options.layer)
  File "/var/www/vhosts/tileforge/private/veloland/veloland/tilecloud/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 347, in gene
    'nb_tiles': nb_tiles if meta else count_metatiles.nb,
UnboundLocalError: local variable 'nb_tiles' referenced before assignment
(tilecloud)tileforge@ip-10-244-189-176:/var/www/vhosts/tileforge/private/veloland/veloland/tilecloud$ time ./bin/generate_tiles -c tilegeneration/config_iphone.yaml -z 23-25 --cache iphone -l Veloland --role
 master
Traceback (most recent call last):
  File "./bin/generate_tiles", line 12, in <module>
    load_entry_point('tilecloud-chain==1.0.0dev1', 'console_scripts', 'generate_tiles')()
  File "/var/www/vhosts/tileforge/private/veloland/veloland/tilecloud/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 421, in main
    generate.gene(options, gene, options.layer)
  File "/var/www/vhosts/tileforge/private/veloland/veloland/tilecloud/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 347, in gene
    'nb_tiles': nb_tiles if meta else count_metatiles.nb,
UnboundLocalError: local variable 'nb_tiles' referenced before assignment
```

**Comment by ochriste** [comment]
error happens when generating the report when sns is configured
